apiVersion: v1
kind: ConfigMap
metadata:
  name: asesoria-config
  namespace: asesoria-inmobiliaria
data:
  NODE_ENV: production
  PORT: "4000"
  WEB_ORIGIN: https://asesoriainmobiliariajb.com
  PUBLIC_API_URL: https://asesoriainmobiliariajb.com
  API_INTERNAL_URL: http://api-service:4000
  NEXT_PUBLIC_API_URL: https://asesoriainmobiliariajb.com
  JWT_EXPIRES_IN_SECONDS: "86400"
  STORAGE_ENDPOINT: minio-service
  STORAGE_PORT: "9000"
  STORAGE_USE_SSL: "false"
  STORAGE_BUCKET: inmobiliaria-assets
  STORAGE_REGION: us-east-1
  STORAGE_AUTO_CREATE_BUCKET: "true"
  STORAGE_MAX_FILE_SIZE: "25000000"
  STORAGE_MAX_FILE_COUNT: "20"
  PROPERTY_IMAGE_MAX_FILE_SIZE: "5000000"
  PROPERTY_360_MAX_FILE_SIZE: "15000000"
  PAYMENT_PROVIDER: mock
  WOMPI_REDIRECT_URL: https://asesoriainmobiliariajb.com/mi-cuenta
  CYBERVESTIGIO_RETURN_URL: https://asesoriainmobiliariajb.com/mi-cuenta
